option domain-name "example.org";
option domain-name-servers ns1.example.org, ns2.example.org;

default-lease-time 600;
max-lease-time 7200;

ddns-update-style none;






subnet 10.0.1.0 netmask 255.255.255.0 {

    range 10.0.1.2 10.0.1.99;

    option routers 10.0.1.1;

    option domain-name-servers 10.0.1.1;

    default-lease-time 600;

    max-lease-time 7200;
}

host vm101 {
    hardware ethernet 00:0c:29:53:26:2e;
    fixed-address 10.0.1.101;
}

host vm102 {
    hardware ethernet 00:0C:29:FB:3F:84;
    fixed-address 10.0.1.102;
}

host vm103 {
    hardware ethernet 00:0c:29:66:cd:07;
    fixed-address 10.0.1.103;
}

host vm104 {
    hardware ethernet 00:0c:29:4e:24:6f;
    fixed-address 10.0.1.104;
}
